services:
  pagerepository:
      class: Doctrine\ORM\EntityRepository
      factory: ["@doctrine.orm.default_entity_manager", getRepository]
      arguments:
          - AcmeNewsBundle\Entity\News

  acme.news.service:
    class: AcmeNewsBundle\Services\NewsService
    arguments:
      - "@pagerepository"
